### ISSUE TITLE
tritondse for fuzzing

### ISSUE THREAD

**Issue by vanhauser-thc** [quarkslab/pastis#2]
The pastis setup is pretty complex.
I am looking for an easy symbolic/concolic solution that could be integrated into afl++, and maybe tritondse could be it.
could you give me some pointers what would be needed to get tritondse running on a target with some input?
That way I would easier understand how to form a custom mutator around it.
that would be great!

**Comment by RobinDavid** [comment]
Hello @vanhauser-thc.
That's an interesting question. If you want to use symbolic execution as a mutator I guess you're not interested by the symbolic executor to explore the program, you only want it to execute the program on an input and to generate new ones for AFL++?

If so, you can have a look at the [``SymbolicExecutor`` object](https://quarkslab.github.io/tritondse/api/executor.html) which performs a the symbolic execution but do not solve constraints. For that, you have to use a [``SeedManager``](https://quarkslab.github.io/tritondse/api/explorator.html#seedmanager) that is in charge on negating branching condition based on the current coverage state. The API function exposed is ``post_execution``, but the one you would be probably interested into is [``__iter_new_paths``](https://github.com/quarkslab/tritondse/blob/main/tritondse/seeds_manager.py#L200).

*(Normally all that is done automatically by the ``SymbolicExplorator`` object)*.

If you're interested I can expose the function in the API, and write a small code snippet that take a program+input, and generate new inputs out of that, but I am not sure about what you want the symbolic to do for AFL++ ?

**Comment by vanhauser-thc** [comment]
I was already a step ahead of myself :-)

First I would like to test tritondse how it performs in solving various challenges and how long it takes to solve them.
I have a little benchmark setup for this at https://github.com/AFLplusplus/fuzzer-challenges

For this I needs actually something simple, a setup that takes a binary and an input and then generates new inputs for the paths not taken.
Is that something simple to do? I guess something like that already exists?

If tritondse is at least somewhat near other solutions I would prefer to implement a solver in that because the API gives me better control at runtime in comparison to what symcc/symqemu/fuzzolic/etc. would allow me to do (at least it looks like that).

Thanks!

**Comment by vanhauser-thc** [comment]
got something basic working, continuing my issues at https://github.com/quarkslab/tritondse/issues/1 :-)
